### ISSUE TITLE
Information missing from WAL records that is needed by primary

### ISSUE THREAD

**Issue by hlinnaka** [zenithdb/zenith#21] opened 2021-04-09 14:02 UTC
Some WAL records leave out information that is not needed in replica, but is still needed by the primary. That's a problem with Zenith, where we rely on the WAL redo to reconstruct a page not only for replicas, but for the original primary instance, too.

I went through all the *_mask() functions, and all the problematic cases seem to be in the heapam:

- commandid is set to 1 in heap insert/update/delete records
- speculative token is not WAL-logged

**Comment by kelvich** [comment] 2021-07-08 09:23
That is handled now by `PD_WAL_LOGGED` mechanism. We may try to use different mechanism and suggest patch for community version of postgres.

**Comment by kelvich** [comment] 2021-07-08 09:40
Duplicate of https://github.com/zenithdb/zenith/issues/21

**Closed by kelvich** 2021-07-08 09:40 UTC
Labels: PostgreSQL
