### ISSUE TITLE
Query cancellation (Ctrl-C) doesn't work for a backend stuck in getpage requests.

### ISSUE THREAD

**Issue by hlinnaka** [zenithdb/zenith#1224] opened 2022-02-05 22:30 UTC
Right now we use blocking libpq function, hence nobody calls for CHECK_FOR_INTERRUPTS(). We should use async interface instead and check for interrupts.

(Originally reported by @kelvich)

**Comment by arssher** [comment] 2022-02-09 12:31
dupe of https://github.com/zenithdb/zenith/issues/644

**Closed** 2022-02-09 14:55 UTC
Labels: m/bug-bash-feb22
