### ISSUE TITLE
create_index regression test failure because of duplicates

### ISSUE THREAD

**Issue by lubennikovaav** [zenithdb/zenith#78] opened 2021-04-28 14:11 UTC
https://github.com/zenithdb/zenith/runs/2457481429

**Comment by hlinnaka** [comment] 2021-05-04 12:27
I have a theory now:

0. Current "last written LSN" is 1
1. Relation is truncated, `truncation` WAL record is created, with LSN 2
2. Very soon after that, a SeqScan is performed on the table. The "relsize" request is made to the page server using the last written LSN 1 in the request. 

Because the request LSN is earlier than the truncation WAL record's LSN, the relsize request returns the old size before the truncation. But that's wrong, the truncation should've been visible to the request.

So I think we need to do something like this:

```
@@ -649,6 +788,12 @@ zenith_nblocks(SMgrRelation reln, ForkNumber forknum)
 void
 zenith_truncate(SMgrRelation reln, ForkNumber forknum, BlockNumber nblocks)
 {
+	XLogRecPtr lsn;
+
+	lsn = GetXLogInsertRecPtr();
+	// XLogFlush(lsn);
+
+	SetLastWrittenPageLSN(lsn);
 }
 ```

**Comment by hlinnaka** [comment] 2021-05-04 12:30
To debug this, I hacked the smgr api functions in `pagestore_smgr.c` to also "pass-through" the write and extend calls to md.c, and in the read functions, read the page both from local disk and from page server and compare. That lead me to find this.

Even after that fix, I'm getting failures from that comparison thing; I'll continue to debug those. And I will also polish that hack to compare the pages a bit and create a PR. I think we should have that as a permanent debugging/testing option.

**Comment by knizhnik** [comment] 2021-05-04 12:39
Yeh, I had such version. I forgot why  I have not committed it. May be because I have used it for fixing some particular problem and once it is fixed, I decided that this checking is no needed any more.

I completely agree with you that we should have it as permanent debug option.

**Comment by lubennikovaav** [comment] 2021-05-04 12:50
It's a good idea about missing truncation.
Though, to me, it looks like a different bug, because I don't understand, how it can possibly result in seeing duplicate values.
Well... there can be some crazy scenario where vacuum truncated some last pages and we returned it and data on it, but I don't think it's what we observe.

BTW, I suggest that we introduce a separate test for every scenario we introduce workarounds for.

**Comment by knizhnik** [comment] 2021-05-04 13:07
I wonder if somebody is no able to reproduce the problem with duplicates in catalog with zenith_clog=false?
I run regression tests multiple times but failed to reproduce this problem any more.

**Comment by lubennikovaav** [comment] 2021-05-04 13:13
It failed here https://github.com/zenithdb/zenith/pull/83/checks?check_run_id=2491859802
zenith_clog is disabled

On my laptop, it is reproducible when tests are super-slow (i.e. full debug on pageserver).
But it's also very unstable. It fails on alter_table or create_index tests and not every time.

**Comment by knizhnik** [comment] 2021-05-04 13:18
SO we have a number of hypothesis explaining presence of duplicates:
1. truncation
2. cmin/xmax
3. smgrimmedsync
4. missed index invalidations

From my point of view:
1. Scenario explained by Heiki illustrates real problem, but can it cause duplicates in pg_index? When this relation is truncated?
2. May be. I am storing now CID in xlog record. But may be it is missed somewhere or bug...
3. Unlikely: fsync should not affect normal behavior of the system
4. May be but I do not understand scenario how it can happen?
5.

**Comment by hlinnaka** [comment] 2021-05-04 14:20
> Scenario explained by Heiki illustrates real problem, but can it cause duplicates in pg_index? When this relation is truncated?

Hmm. We should never truncate away pages that contain live tuples, only empty pages. However, when a relation is truncated, if any of the truncated pages are dirty in the buffer pool, we just drop them without writing them out. So this could happen:

1. Tuples are deleted, the page is marked dirty
2. The relation is vacuumed, and the page is truncated away
3. The page is read back with old "last-written LSN", which didn't include the deletion yet

**Comment by lubennikovaav** [comment] 2021-05-05 17:38
The problem is still here and it's still hard to catch. Smaller `shared_buffers` (i use 300) and larger `checkpoint_timeout` setting seem to be helpful.

I managed to catch it in another test
```type_sanity.out     2021-05-05 18:44:50.716319175 +0300
@@ -597,9 +597,10 @@
 FROM pg_class AS p1
 WHERE p1.relnatts != (SELECT count(*) FROM pg_attribute AS p2
                       WHERE p2.attrelid = p1.oid AND p2.attnum > 0);
- oid | relname 
------+---------
-(0 rows)
+  oid  |        relname         
+-------+------------------------
+ 17438 | quad_poly_tbl_ord_idx2
+(1 row)
```
Which makes me think of another hypotesis - we don't replay some visibilitymap_clear().

Most likely, it is not specific to pg_class, it's just easier to catch on catalog table, because cache invalidation triggers relation eviction and reread from pageserver.

**Comment by hlinnaka** [comment] 2021-05-05 18:18
> The problem is still here and it's still hard to catch.

Darn.

> Which makes me think of another hypotesis - we don't replay some visibilitymap_clear().

Yeah, that seems plausible. We are certainly not doing the equivalent of visibilitymap_clear() at the moment, and we should. Would you investigate that, to see if you can write a test case to reproduce it more reliably?

That's unfortunate, as we'll need to parse the heapam WAL records more thoroughly to clear the VM bits. Or perhaps we can just disable the visibility map for now, by returning all-zeros pages or empty relation for any requests on the VM fork in the page server.

**Comment by lubennikovaav** [comment] 2021-05-05 19:41
> Would you investigate that, to see if you can write a test case to reproduce it more reliably?
Sure. I'm working on it now.

**Comment by knizhnik** [comment] 2021-05-05 19:46
> Most likely, it is not specific to pg_class, it's just easier to catch on catalog table, because cache invalidation triggers relation eviction and reread from pageserver.

It really seems to be the most probable case. VM is conservative, so if all-visible bit is set, then Postgres assumes that all objects on the page are visible and do not perform extra visibility checks during index-only scan.

There are no separate WAL records for updating VM. It is updated by redo of insert/delete XLOG records.
So there are three choices:
1. Associate this WAL records also with VM pages
2. Prohibit throwing away VM pages
3. Always return clean VM page from page server

1) may significantly increase amount of storage used for storing WAL at wal-keepers.
In case 2) we still need to solve the problem of restoring VM at new node (either make this node replay non-relational WAL, either implement it in page server).
3) proposed by Hekii seems to be the simplest and still quit efficient solution, because VM pages are not expected to be frequently swapped out. My concern is how we will manged to eventually restore all-visible bits in VM? It seems to be done by vacuum. But if relation is not changed, then vacuum will not be called. And all index-only scans will have to perform redundant visibility checks, which definitely has negative influence on IOS speed.l

**Comment by ericseppanen** [comment] 2021-05-11 06:04
Duplicate? [pg_regress test #222](https://app.circleci.com/pipelines/github/zenithdb/zenith/80/workflows/aefce02c-7085-4138-9f4b-e02b383ecfee/jobs/222)

```text
diff -U3 /home/circleci/project/vendor/postgres/src/test/regress/expected/zenith-vacuum-full.out /tmp/test_output/test_pg_regress/regress/results/zenith-vacuum-full.out
--- /home/circleci/project/vendor/postgres/src/test/regress/expected/zenith-vacuum-full.out	2021-05-10 23:42:13.122393187 +0000
+++ /tmp/test_output/test_pg_regress/regress/results/zenith-vacuum-full.out	2021-05-10 23:43:09.982343425 +0000
@@ -194,8 +194,11 @@
  c      | integer |           |          | 
 Indexes:
     "foo_pkey" PRIMARY KEY, btree (a)
+    "foo_pkey" PRIMARY KEY, btree (a)
+    "foo_b_idx" btree (b)
     "foo_b_idx" btree (b)
     "foo_c_idx" btree (c)
+    "foo_c_idx" btree (c)
 
 vacuum full foo;
 \d foo
@@ -246,8 +249,11 @@
  c      | integer |           |          | 
 Indexes:
     "foo_pkey" PRIMARY KEY, btree (a)
+    "foo_pkey" PRIMARY KEY, btree (a)
+    "foo_b_idx" btree (b)
     "foo_b_idx" btree (b)
     "foo_c_idx" btree (c)
+    "foo_c_idx" btree (c)
 
 vacuum full foo;
 \d foo
```

**Comment by hlinnaka** [comment] 2021-05-11 08:36
> Duplicate? [pg_regress test #222](https://app.circleci.com/pipelines/github/zenithdb/zenith/80/workflows/aefce02c-7085-4138-9f4b-e02b383ecfee/jobs/222)

Yeah, that's the same issue.

**Closed** 2021-07-08 09:28 UTC
