### ISSUE TITLE
test_pageserver_restart failed with `client requested callmemaybe on timeline which does not exist in page server`

### ISSUE THREAD

**Issue by arssher** [zenithdb/zenith#470] opened 2021-08-25 14:49 UTC
Per CI in evidently unrelated PR:
https://app.circleci.com/pipelines/github/zenithdb/zenith/1338/workflows/e393ec8c-d24c-4956-8571-48df9f146865/jobs/7635/steps

Since timeline was there all the time, it seems like the real error was masked by uplevel error message. I've created a PR not hiding it.

**Comment by lubennikovaav** [comment] 2021-08-30 12:04
My PR caught a similar failure in `test_pageserver_restart` 
https://app.circleci.com/pipelines/github/zenithdb/zenith/1407/workflows/39542ce1-975a-4215-873d-9d1ec13ef6ab/jobs/8172/steps

```Aug 30 08:37:25.598 ERRO get_page_at_lsn: Timed out while waiting for WAL record at LSN 0/2763E78 to arrive, location: pageserver::page_service, pageserver/src/page_service.rs:313
Aug 30 08:37:25.660 INFO WAL streaming connection failed (unexpected open layer in the future), retrying in 1 second, location: pageserver::walreceiver, pageserver/src/walreceiver.rs:109```

Is it the same problem?

**Comment by stepashka** [comment] 2021-12-07 14:53
@arssher Does this still happen?

**Comment by hlinnaka** [comment] 2022-01-14 18:45
I haven't seen this happen for a long time, I assume it's been fixed. Possibly a duplicate of https://github.com/zenithdb/zenith/issues/611. Closing.

**Closed by hlinnaka** 2022-01-14 18:45 UTC
Labels: t/bug, c/pageserver
