### ISSUE TITLE
Detach tenant

### ISSUE THREAD

**Issue by kelvich** [zenithdb/zenith#899] opened 2021-11-17 14:17 UTC

**Comment by LizardWizzard** [comment] 2021-12-23 15:15
These days I was going back and forth between detach implementation approaches and this is the write up on what I think will work correctly.

Detach process is the following.

1. Checkpoint
2. Spin up new pageserver (or skip if moving to existing one)\
3. Attach timeline to new pageserver
4. Ask pageserver to connect to safekeeper (e.g. via callmemaybe by migration script)
5. Wait for pageserver to catch up
6. Restart compute with new pageserver conn string in config
7. Detach timeline from old pageserver.

The problem is in performing safe detach. When we ask pageserver to detach a timeline we must be sure that there is no unsynced data.
This can be done via pre-migrate api call. This call makes a checkpoint and disables further checkpoints for this timeline for two reasons:
* We do not want to have concurrent checkpointers in new and old pageserver
* We do not want to advance remote_consistent_lsn reported to safekeeper so it contains all the needed WAL to feed it to the new pageserver.

* Cons: If migration is stuck, is it a problem for pageserver/safekeepr to live without a checkpoint? WEecan leave checkpoints enabled, but disable uploading (this won't advance remote consistent lsn).

So when detach is called on the old pageserver if pre-migrate was called earlier pageserver can be sure that there is no unsynced data and can safely stop walreceiver and remove timeline data.

Why pageserver needs to stop walreceiver, whouldn't it be stopped by safekeeper?

Currently there is some logic in safekeeper that stops replication connections when there is no active compute and the replica is caught up.
However these prerequisites do not match detach scenario. Currently when migration is performed compute is restarted, but for sure it is desired to avoid that.
In fact currently if compute is restarted quickly enough replication logic in safekeeper won't see that even if replica is caught up. But replica may be a little behind and this condition wont be triggered, so after compute restart replication continues to both, old and new pageserver

That said, old pageserver cannot rely on safekeeper to shutdown the replication connection, so pageserver must terminate walreceiver by itself.
As I mentioned above, it is safe because there wont be any new data that is missing from combination of s3 and safekeeper.

@kelvich @arssher Please review my reasoning

**Comment by arssher** [comment] 2021-12-23 16:40
> However these prerequisites do not match detach scenario.

It is true that safekeeper in the presense of compute should ensure not just connection to some pageserver, but to the particular one, specified by the compute -- that's a bug in current impl. However, the idea itself of using compute to switch the connection seems like a good one, you have to change pageserver address at some point anyway; and compute restart is not actually necessary here.

**Comment by LizardWizzard** [comment] 2021-12-23 18:24
@arssher Then we should unconditionally disconnect all replicas excluding new primary pageserver, right? Looks weird to me, this way we should support read only replicas in a special way to avoid breakage of their connections. In my opinion here pageserver knows everything needed when detach command is called. What do you think?

**Comment by LizardWizzard** [comment] 2021-12-24 12:55
We've discussed this and decided to start with detach responsible for breaking replication connection. Other notes:
1. Lets combine replication start with attach command
2. Concurrent checkpointing to s3 wont produce similar files, because checkpoint lsn is determined from current value of `last_record_lsn` which is not synced between different pageservers. This way we won't loose any data but directory structure contract will be broken. So in general it should be possible to build the correct structure again, but this is out of scope for now (because we're trying to avoid this situation, but if that happens it is not fatal)

**Closed** 2022-03-10 12:40 UTC
Labels: c/storage/pageserver
