### ISSUE TITLE
wal_keeper tests are freezing sometimes

### ISSUE THREAD

**Issue by kelvich** [zenithdb/zenith#156] opened 2021-05-18 13:14 UTC
Symptoms:

wal_keeper closes replication connection to the pageserver without any obvious reason (no error in logs) after some amount of time. Then pageserver reconnects and that connection closes right after 'START REPLICATION ' command also without clear reason.

I faced this few times on my laptop but since same code was working okay in CI I decided that it is macos-related.
@ericseppanen pointed out that he observes same behavior on linux too and that it is non-deterministic failure, but happens only after  746f667

**Comment by lubennikovaav** [comment] 2021-05-18 13:23
Hmm. Maybe this commit in vendor/postgres is the reason?
2a6c17f1e013ecb5a480ad3e9db24f6b2972b8bz

I could have rushed with removing this code.

**Comment by kelvich** [comment] 2021-05-18 16:22
So for the problem that I see on macOS (pretty deterministically) I bisected failed test to commit 4b46693 which changes async socket handling to the sync one. Nothing in the patch itself looked suspitious so I started to look what is actually happens with the connection.

Running `tcpflow -D -i lo0 -c port 54321` on the broken version yields following:

```
127.000.000.001.59782-127.000.000.001.54321: 
0000: 0000 0067 0003 0000 636c 6965 6e74 5f65 6e63 6f64 696e 6700 5554 4638 006f 7074  ...g....client_encoding.UTF8.opt
0020: 696f 6e73 002d 6320 7a74 696d 656c 696e 6569 643d 6633 3431 6132 6638 6135 3361  ions.-c ztimelineid=f341a2f8a53a
0040: 3263 6664 6332 6230 6366 6364 3031 6562 3437 3237 0072 6570 6c69 6361 7469 6f6e  2cfdc2b0cfcd01eb4727.replication
0060: 0074 7275 6500 00                                                                .true..

127.000.000.001.54321-127.000.000.001.59782: 
0000: 5200 0000 0800 0000 005a 0000 0005 49 R........Z....I

127.000.000.001.59782-127.000.000.001.54321: 
0000: 5100 0000 1449 4445 4e54 4946 595f 5359 5354 454d 00 Q....IDENTIFY_SYSTEM.

127.000.000.001.54321-127.000.000.001.59782: 
0000: 5400 0000 6f00 0473 7973 7465 6d69 6400 0000 0000 0000 0000 0019 ffff ffff ffff  T...o..systemid.................
0020: 0000 7469 6d65 6c69 6e65 0000 0000 0000 0000 0000 1700 04ff ffff ff00 0078 6c6f  ..timeline...................xlo
0040: 6770 6f73 0000 0000 0000 0000 0000 19ff ffff ffff ff00 0064 626e 616d 6500 0000  gpos...................dbname...
0060: 0000 0000 0000 0019 ffff ffff ffff 0000 4400 0000 3400 0400 0000 1336 3936 3336  ................D...4......69636
0080: 3438 3236 3333 3130 3736 3631 3632 0000 0001 3000 0000 0a30 2f30 3030 3030 3030  48263310766162....0....0/0000000
00a0: 30ff ffff ff43 0000 0014 4944 454e 5449 4659 5f53 5953 5445 4d00 5a00 0000 0549  0....C....IDENTIFY_SYSTEM.Z....I

127.000.000.001.59782-127.000.000.001.54321: 
0000: 5100 0000 2953 5441 5254 5f52 4550 4c49 4341 5449 4f4e 2050 4859 5349 4341 4c20  Q...)START_REPLICATION PHYSICAL 
0020: 302f 3136 3039 3631 3000                                                         0/1609610.

127.000.000.001.54321-127.000.000.001.59782: 
0000: 5700 0000 0700 0000  W.......
```

So wal_acceptor got `START_REPLICATION` command, responded to it with `BeMessage::Copy` and suddenly closed connection. Compare this with the same dump on previous commit:

```
127.000.000.001.60155-127.000.000.001.54321: 
0000: 5100 0000 2953 5441 5254 5f52 4550 4c49 4341 5449 4f4e 2050 4859 5349 4341 4c20  Q...)START_REPLICATION PHYSICAL 
0020: 302f 3136 3039 3631 3000                                                         0/1609610.

127.000.000.001.54321-127.000.000.001.60155: 
0000: 5700 0000 0700 0000  W.......


127.000.000.001.54321-127.000.000.001.60155: 
0000: 6400 0020 6d77 0000 0000 0163 8230 0000 0000 0163 a280 0002 659b 160f 750e 3120  d.. mw.....c.0.....c....e...u.1 
0020: 0000 1c02 0000 e081 6301 0000 0000 b000 0000 8207 a8c5 0010 0000 0020 0000 047f  ........c.................. ....
0040: 0600 00af 3300 0000 4000 0001 0000 0000 0000 0000 0000 0000 0008 0000 0000 0000  ....3...@.......................
0060: 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000  ................................
<...>
```

In this case wal_acceptor sends actual `CopyData` right after `Copy` without any problems. Looking in the code in between this messages:

```rust
self.stream.set_nonblocking(true).unwrap();
let read_result = self.stream.read(&mut self.inbuf);
self.stream.set_nonblocking(false).unwrap();

match read_result {
    Ok(0) => break,
    Ok(_) => {
        if let Some(FeMessage::CopyData(m)) = self.parse_message()? {
            self.timeline()
                .add_hs_feedback(HotStandbyFeedback::parse(&m.body))
        }
    }
    Err(ref e) if e.kind() == io::ErrorKind::WouldBlock => {}
    Err(e) => {
        return Err(e);
    }
}
```

Error is not raised so we got `Ok(0)` for some reason. I always thought that this only happens on closed connection, but connection is actually open. Let's look to strace:

```

# dtruss -p 52278
<...>
sendto(0x8, 0x7F96E7812000, 0x8)		 = 8 0
ioctl(0x8, 0x8004667E, 0x70001013AB1C)		 = 0 0
recvfrom(0x8, 0x7F96E78082A6, 0x0)		 = 0 0
ioctl(0x8, 0x8004667E, 0x70001013AB1C)		 = 0 0
<...>
```

Okay, now it is clear that we are trying to read 0 bytes from socket and recvfrom() behavior in this case isn't properly defined: macOS man just silent about this corner case, but Linux man actually mentions that with verb 'may':

```
The value 0 may also be returned if the requested number of bytes to receive from a stream socket was 0.
```

So as a dirty solution let's just do nothing when `Ok(0)` arrives, that should fix the issue. But generally it is better not to call `recvfrom()` with 0 len: either learn reader not to do that or call recv with `MSG_PEEK` on some static buffer as a crutch.

**Comment by ericseppanen** [comment] 2021-05-18 16:43
I happened to run `ps` on my machine (Linux; Ubuntu 20.04) while a test was in the hung state, and found only two `wal_acceptor` processes running. So the attempted connections are failing because the process on that port is not even running.

**Comment by ericseppanen** [comment] 2021-05-18 16:46
On my branch (PR #151) the nonblocking socket code has been removed. I wonder whether that would help with the macOS problem?

Note that branch `network_refactor` does not include commit 746f667. The rebase has only very minor conflicts; let me know if you'd like me to start another branch containing 746f667 and my PR151 network code.

**Comment by knizhnik** [comment] 2021-05-18 17:37
The problem was caused by incorrect replacement of tokio::net::TcpStream.try_read_buf
This method reads data into Buf  up to its capacity and set length to the amount of received bytes.
Now it is replaced with std::net::TcpStream.read which reads into the slice with size equal to buffer length.
The length of self.inbuf is  determined by size of previously received message. And then this length is not altered by read() unlike  try_read_buf. When received size is not zero, then we call parse_message, which is looking at buffer length. But this buffer length is not equal to the actual amount of received data. It is just length of previous message!

So one of the possible fix is to change buffer length to its capacity before calling read() and then alter this length (using unsafe set_len???) with actual amount of received bytes. Dumn!

**Comment by kelvich** [comment] 2021-05-18 18:36
Also there was another problem with wal_acceptor tests: 21ea70c8f547

And original issue from this thread is fixed in upcoming https://github.com/zenithdb/zenith/pull/151 so we can just wait while it lands in pageserver.

**Comment by ericseppanen** [comment] 2021-05-21 23:14
I think everything here is fixed now, and this issue can be closed.

21ea70c fixed the problem where everything hung if wal_acceptor 0 was stopped.
#151 fixed the problem caused by nonblocking network reads of incorrect size.

**Closed by ericseppanen** 2021-05-21 23:14 UTC
