### ISSUE TITLE
Basic safekeeper performance numbers

### ISSUE THREAD

**Issue by arssher** [zenithdb/zenith#799] opened 2021-10-25 15:53 UTC
Let's have a look at safekeeper performance. Like

- Create 3 VMs, deploy and run 3 safekeepers on them.
- Create VM with postgres configured to run with safekeepers but without pageserver (`zenith.page_server_connstring` not set)
- run pgbench -i -s 400  , (creates db about 5GB size), see how it goes -- time to load.
- Run pgbench for a couple of hours. With e.g. -c 32. Log tps somewhere (-P 1 shows progress), maybe create graph with it. Check out CPU, memory usage.

If everything goes ok, it would be good to look at metrics exposed to prometheus.

Compare the same with Postgres synchronous replicas (synchronous_standby_names=any 2(s1, s2, s3)) instead of safekeepers.

**Comment by petuhovskiy** [comment] 2021-11-01 19:48
Ran pgbench for one hour on AWS instances with this configuration: 3x safekeeper on i3.large, 1x compute on i3.large.

<details><summary>postgresql.conf</summary>

```
max_wal_senders=10
wal_log_hints=on
max_replication_slots=10
hot_standby=on
shared_buffers=8192MB
fsync=off
max_connections=100
wal_sender_timeout=0
wal_level=replica
listen_addresses='127.0.0.1'
port=5432
wal_keep_size=10TB
shared_preload_libraries=zenith
zenith.page_server_connstring=''
zenith.zenith_tenant=c9bc8b6ea42cba805c62ee42c1637761
zenith.zenith_timeline=d03d475996d127df7839a796c3762df0
synchronous_standby_names = 'walproposer'
wal_acceptors = '172.32.29.146:6500,172.32.24.189:6500,172.32.27.7:6500'
```

</details>

Results:
```
pgbench -i -s 400
...
done in 230.75 s (drop tables 0.00 s, create tables 0.01 s, client-side generate 80.00 s, vacuum 100.50 s, primary keys 50.23 s).

pgbench -c 32 -P 1 -T 3600
...
pgbench (PostgreSQL) 14.0
transaction type: <builtin: TPC-B (sort of)>
scaling factor: 400
query mode: simple
number of clients: 32
number of threads: 1
duration: 3600 s
number of transactions actually processed: 1266470
latency average = 90.886 ms
latency stddev = 56.137 ms
initial connection time = 75.879 ms
tps = 351.663208 (without initial connection time)
```

Also built a graph of TPS by run time, available [here](https://colab.research.google.com/drive/1rUyDr6vaprI4dLwWTFTETHOGBd2W2KOh?usp=sharing). This graph shows that performance drops fast from ~1000 TPS to ~300 TPS in 10 minutes.

**Comment by petuhovskiy** [comment] 2021-11-02 14:13
Ran pgbench again on almost the same config, this time it got 700 TPS and more stable graph. Results:
```
pgbench -i -s 400
...
done in 205.79 s (drop tables 0.00 s, create tables 0.01 s, client-side generate 74.78 s, vacuum 91.41 s, primary keys 39.59 s).

pgbench -c 32 -P 1 -T 3600
...
pgbench (PostgreSQL) 14.0
transaction type: <builtin: TPC-B (sort of)>
scaling factor: 400
query mode: simple
number of clients: 32
number of threads: 1
duration: 3600 s
number of transactions actually processed: 2517334
latency average = 45.729 ms
latency stddev = 12.887 ms
initial connection time = 70.481 ms
tps = 699.193058 (without initial connection time)
```

Graph available [here](https://colab.research.google.com/drive/1jatwPAJ1zwub4TFWYHWZwm97iYVpdYVX#scrollTo=PkWbCqdPqzk0). It seems that the only difference from the previous run was the size of the root EBS volume, which shouldn't affect anything. It's not very clear what happened in the previous run. The results are still not very good and need to be investigated.

**Comment by petuhovskiy** [comment] 2021-11-04 10:30
Two more runs with the same configurations:
- [1293 TPS](https://gist.github.com/petuhovskiy/2d5babbcc0df592b1ca067460e728822)
- [239 TPS](https://gist.github.com/petuhovskiy/994946512405d18962cd4b2d83c96048)

Results are very unstable now and probably we should look into that before continuing benchmarks with walproposer+safekeepers.

**Comment by petuhovskiy** [comment] 2021-11-05 16:34
I did the same pgbench test with postgres synchronous replication on the same VMs setup, it got [1502 TPS](https://gist.github.com/petuhovskiy/872946345d337031cb864a5c805e8766). It's not that far away from best yet result of walproposer+safekeepers (1293 TPS), but we still should stabilize performance of our approach for better comparison.

**Comment by petuhovskiy** [comment] 2021-11-12 19:11
As https://github.com/zenithdb/zenith/issues/780 is fixed, performance should be stable now. I ran usual pgbench on usual walproposer+safekeeper setup on the same configuration with i3.large instances, it got [1005 TPS](https://gist.github.com/petuhovskiy/e08bcdc258dd0365e3ac51c2a214c20a). But something was not right there, Prometheus metrics looked like compute hit OOM and benchmark was not doing anything for the last 10 minutes.
<img width="930" alt="image" src="https://user-images.githubusercontent.com/8150127/141514614-c36fe01c-f086-4d1a-94ba-40167fe71d1e.png">

Looking at pg.log, it seems that truncateLsn stuck and WalMessage queue overflowed. This happened because of the straggling safekeeper, I'll take a closer look next week. 

Logs to investigate:
- [pg.log](https://large-logs.storage.yandexcloud.net/nov12/pg.log)
- [pgbench.log](https://large-logs.storage.yandexcloud.net/nov12/pgbench.log)
- [postgresql.conf](https://large-logs.storage.yandexcloud.net/nov12/postgresql.conf)
- [sk1-172.32.28.232.log](https://large-logs.storage.yandexcloud.net/nov12/sk1-172.32.28.232.log)
- [sk2-172.32.23.117.log](https://large-logs.storage.yandexcloud.net/nov12/sk2-172.32.23.117.log)
- [sk3-172.32.28.38.log](https://large-logs.storage.yandexcloud.net/nov12/sk3-172.32.28.38.log)

**Comment by petuhovskiy** [comment] 2021-11-18 17:02
I switched to using c5.2xlarge for compute instance, it has 8cpu and 16gb ram and gp2 disk (which is much slower compared to i3.large, but should be enough for compute). Also Grafana now shows flush_lsn and commit_lsn from safekeepers, which is useful for understanding how far behind one of the safekeepers is. 


Below are several tests results:
- walproposer got OOM once again and had [1148 TPS](https://gist.github.com/petuhovskiy/8fa8b5604adc756a3edab97d54ace3cc)
- synchronous replication had [4871 TPS](https://gist.github.com/petuhovskiy/f8e498e5b232e96b748e36ceaa81ef98), which means we should be able to improve walproposer+safekeepers performance by about 4 times
- local postgres with default config had [1478 TPS](https://gist.github.com/petuhovskiy/81226dcd1b773045c9a20747aa7d9aca)
- walproposer+safekeepers on `pgbench -c 32 -j 2 -N` had [920 TPS](https://gist.github.com/petuhovskiy/ad69c1ae255424b49d4ffd37da9f9ec2), not sure why it's lower than previous runs
- walproposer+safekeepers on `pgbench -c 1 -j 2 -N` had [904 TPS](https://gist.github.com/petuhovskiy/926195381958af98bd7e3c07fbb9f1ee)

Some TPS graphs don't look stable enough, I think I'll try to adjust postgresql.conf and pgbench arguments to get more consistent results.

**Comment by petuhovskiy** [comment] 2021-11-26 13:46
In the previous runs, checkpointer could generate a lot of WAL in the middle of the benchmark and affect TPS. I increased checkpoint_timeout and now running pgbench only for 10 minutes, so checkpointer will not run during benchmark. That produces more stable results now.

I also found out another thing affecting performance, which is EC2 instances deploy randomness. It looks like performance can vary depending on how well instances are created. That is, I get consistent pgbench results if I don't change EC2 instances and can get a different (TPS lower by 40%, for example) result if I'll recreate them and run the same test on the new instances. It's probably connected to latency between nodes, so I added ping to the reports. Below benchmarks are all done on the same instances.

walproposer + safekeepers results:
- `pgbench -c 1 -N` -- [1615 TPS](https://gist.github.com/petuhovskiy/ad278b2a8661ee80adc15fdbf19eb602)
- `pgbench -c 32 -N` -- [1687 TPS](https://gist.github.com/petuhovskiy/ff3c23c3f8b8dfac84902bc9acb7ed55)
- `pgbench -c 32 -N` -- [1754 TPS](https://gist.github.com/petuhovskiy/8c8db95619767fba2d0fe93916a75be6)

postgres with ANY 2 of 3 synchronous replication:
- `pgbench -c 1 -N` -- [1682 TPS](https://gist.github.com/petuhovskiy/01445f604f233c62020d7d2504d75eb9)
- `pgbench -c 1 -N` -- [1662 TPS](https://gist.github.com/petuhovskiy/4bde1dac0915e8c246f2ec33340109b5)
- `pgbench -c 2 -N` -- [3217 TPS](https://gist.github.com/petuhovskiy/3a4e2beab2ccc55ca28bd3d04113c058)
- `pgbench -c 32 -N` -- [14623 TPS](https://gist.github.com/petuhovskiy/8be15e147c6d1cce9e78c3f50441ccdd)



Also, if anyone is interested, here's my repo with deployment scripts: https://github.com/petuhovskiy/zenith-perftest

**Comment by MMeent** [comment] 2021-12-01 11:03
> randomness. It looks like performance can vary depending on how well instances are created

Instance placement is indeed quite important when considering network latency, jitter and congestion, and (although I haven't actively experienced it on AWS at my previous job) noisy neighbors could also be a cause. Did you try launching the configuration within a 'cluster' placement group and then check for result consistency?

**Comment by petuhovskiy** [comment] 2021-12-07 11:46
> Instance placement is indeed quite important when considering network latency, jitter and congestion, and (although I haven't actively experienced it on AWS at my previous job) noisy neighbors could also be a cause. Did you try launching the configuration within a 'cluster' placement group and then check for result consistency?

I've tried deploying instances with 'cluster' placement group several times, these deployments seem to have better overall performance, but still not very consistent and results can vary +-15% between different deployments.

**Comment by petuhovskiy** [comment] 2021-12-07 13:07
I experimented with async walproposer implementation https://github.com/zenithdb/postgres/pull/105, the results are a bit better, but still far behind synchronous replication.

walproposer(async patch) + safekeepers:
- `pgbench -c 1 -N` -- [1717 TPS](https://gist.github.com/petuhovskiy/212f9e0640ece8d6185c5158b22a8e9c)
- `pgbench -c 2 -N` -- [2799 TPS](https://gist.github.com/petuhovskiy/592866e460b3ebe14f9241fd2fbd14db)
- `pgbench -c 4 -N` -- [2916 TPS](https://gist.github.com/petuhovskiy/b9b5966532d13d262e25f67a23ff3833)
- `pgbench -c 8 -N` -- [2946 TPS](https://gist.github.com/petuhovskiy/1254cd7ca34ad318e7ba264c4ac0284b)
- `pgbench -c 32 -N` -- [2896 TPS](https://gist.github.com/petuhovskiy/276156e45ed046e2cc87779e415e7d7a)

postgres with ANY 2 of 3 synchronous replication:
- `pgbench -c 1 -N` -- [2012 TPS](https://gist.github.com/petuhovskiy/de7bf8ea7a0872569941257a7f8e5fa3)
- `pgbench -c 2 -N` -- [3436 TPS](https://gist.github.com/petuhovskiy/0efab9db53de142bd472148d743669e4)
- `pgbench -c 4 -N` -- [6289 TPS](https://gist.github.com/petuhovskiy/a37354ff23a50f5b32a739cc2e9211fd)
- `pgbench -c 8 -N` -- [9042 TPS](https://gist.github.com/petuhovskiy/ea84d706be311cd95344ce98bb6c210d)

**Comment by petuhovskiy** [comment] 2021-12-07 16:46
I ran tests again but with control files persist patch https://github.com/zenithdb/zenith/pull/966, the results are now same or even better than synchronous replication. The only odd thing is that synchronous replication don't have 14k TPS as it was before, maybe it's because of the unlucky deployment (one safekeeper instance has 2x slower fsyncs) or caused by my patch which adds logs for every message.

walproposer(async patch) + safekeepers(control sync patch):
- `pgbench -c 1 -N` -- [2026 TPS](https://gist.github.com/petuhovskiy/0a7e7288a2c127d570f55a4074296602)
- `pgbench -c 2 -N` -- [3537 TPS](https://gist.github.com/petuhovskiy/2aa035739ff732d35902d483ad353e3c)
- `pgbench -c 4 -N` -- [6045 TPS](https://gist.github.com/petuhovskiy/e3ca2d9f9a50dba1a13ddce69a8646b3)
- `pgbench -c 8 -N` -- [7889 TPS](https://gist.github.com/petuhovskiy/f2a234ded858514d64274932074213d5)
- `pgbench -c 32 -N` -- [8476 TPS](https://gist.github.com/petuhovskiy/167fb8a685b99b827fa563ba5053be1c)

postgres with ANY 2 of 3 synchronous replication:
- `pgbench -c 1 -N` -- [1926 TPS](https://gist.github.com/petuhovskiy/e8e23270216b93218e622b2ca6420d77)
- `pgbench -c 2 -N` -- [3366 TPS](https://gist.github.com/petuhovskiy/5809bc3b112dd75a359e0e35479b9a7d)
- `pgbench -c 4 -N` -- [5786 TPS](https://gist.github.com/petuhovskiy/56625348ff6f9b1d31e40bf332cd7302)
- `pgbench -c 8 -N` -- [8748 TPS](https://gist.github.com/petuhovskiy/2c8a3fc6072e2cad9956223455b47431)
- `pgbench -c 32 -N` -- [8779 TPS](https://gist.github.com/petuhovskiy/f378d47d43f0af6252500401ef75f6fc)

**Comment by petuhovskiy** [comment] 2021-12-09 10:32
Added some basic info about message sizes in both tests and did another run. Also did more runs with many connections.

walproposer(async patch) + safekeepers(control sync patch):
- ```pgbench -c 1 -N``` –– [2106 TPS](https://gist.github.com/petuhovskiy/888479145ab2a2c6fdf540ae487768cb)
- ```pgbench -c 2 -N``` –– [3701 TPS](https://gist.github.com/petuhovskiy/d97e6611da073267805ed8b89cb115ce)
- ```pgbench -c 4 -N``` –– [6297 TPS](https://gist.github.com/petuhovskiy/35b18b2566ff507e54d9ec2093a45c96)
- ```pgbench -c 8 -N``` –– [8861 TPS](https://gist.github.com/petuhovskiy/03c1ad680c747151f255865c2d30f264)
- ```pgbench -c 32 -N``` –– [9474 TPS](https://gist.github.com/petuhovskiy/562a81a5945a3b054659351c295ba4b3)
- ```pgbench -c 32 -N``` –– [8600 TPS](https://gist.github.com/petuhovskiy/c98a00f1d68b45afcf623e48849715ce)
- ```pgbench -c 32 -N``` –– [9107 TPS](https://gist.github.com/petuhovskiy/e453fdea728bf13f1e01fa3ae20c1e94)
- ```pgbench -c 32 -N``` –– [9254 TPS](https://gist.github.com/petuhovskiy/7f2ba55cfb5cb24d83206b0e7dea31f7)

postgres with ANY 2 of 3 synchronous replication:
- ```pgbench -c 1 -N``` –– [1794 TPS](https://gist.github.com/petuhovskiy/a03b67ed1764567274a13abc355f2c02)
- ```pgbench -c 2 -N``` –– [3431 TPS](https://gist.github.com/petuhovskiy/4bc7bf5efb9f7fd93dff02ccb5092cd3)
- ```pgbench -c 4 -N``` –– [6020 TPS](https://gist.github.com/petuhovskiy/bec38db3a99892f94efde7c89e43a80c)
- ```pgbench -c 8 -N``` –– [7740 TPS](https://gist.github.com/petuhovskiy/40fe6b89980f7f1b6f5babc6c946902b)
- ```pgbench -c 32 -N``` –– [8854 TPS](https://gist.github.com/petuhovskiy/ca88da6219570def6b0a980dac5863d7)
- ```pgbench -c 32 -N``` –– [14751 TPS](https://gist.github.com/petuhovskiy/9a919a34d90251ee4f9a020e6d607c53)
- ```pgbench -c 32 -N``` –– [14515 TPS](https://gist.github.com/petuhovskiy/680965e13e24af5472208d95e369917e)
- ```pgbench -c 32 -N``` –– [14179 TPS](https://gist.github.com/petuhovskiy/85bc8981ef402e2e6b8a6055cb6d305e)

The results are similar to the previous runs, but it seems that synchronous replication with 32 connections can give different results. Also TPS graphs of synchronous replication is very fluctuating, don't know why.
I also tried to disable logs and it seems that it doesn't affect anything, so I'll keep them for now.

**Comment by petuhovskiy** [comment] 2022-01-10 20:25
Did another run on main to reassure that performance hasn't degraded.

walproposer on main:
- ```pgbench -c 1 -N``` –– [2140 TPS](https://gist.github.com/petuhovskiy/637aa290848c01ea2319a23ec4e28fa2)
- ```pgbench -c 8 -N``` –– [8386 TPS](https://gist.github.com/petuhovskiy/07f86fb63bf6b4fa54e5b1fdd7bdf0ba)
- ```pgbench -c 32 -N``` –– [9499 TPS](https://gist.github.com/petuhovskiy/fb0c296da34e3cba7a512132520be925)
- ```pgbench -c 32 -N``` –– [9449 TPS](https://gist.github.com/petuhovskiy/6af590dcea047a34128b714f02bf1152)

postgres with ANY 2 of 3 synchronous replication:
- ```pgbench -c 1 -N``` –– [1986 TPS](https://gist.github.com/petuhovskiy/820a25c037ba651e49accf0f841ddfea)
- ```pgbench -c 8 -N``` –– [9428 TPS](https://gist.github.com/petuhovskiy/d26aae1daeb9b8fcf1f60564bb0ffa6a)
- ```pgbench -c 32 -N``` –– [14408 TPS](https://gist.github.com/petuhovskiy/69d288117c9c05b499e729ad43b8f64f)
- ```pgbench -c 32 -N``` –– [14694 TPS](https://gist.github.com/petuhovskiy/b810d88e81e9abc54bbca872b7494dd6)

The results are basically the same as before. There is still 9k vs 14k difference in TPS on 32 connections, I'll try to address this soon. I'm closing #960 because that was an issue when performance was a lot worse and it's not relevant now.

**Closed** 2022-01-18 19:51 UTC
Labels: c/safekeeper
