### ISSUE TITLE
CircleCI: produce binary build artifacts for postgres + zenith

### ISSUE THREAD

**Issue by ericseppanen** [zenithdb/zenith#128] opened 2021-05-11 22:38 UTC
The output of a successful CircleCI build should be some binary package(s) that can be installed to run postgres and zenith.

They should be used as inputs for CI test jobs, as well as downstream builders, such as for cloud deployment.

The goal is **ship exactly what you test**, so we want to avoid any other pipelines duplicating this work.

For now, the binary artifacts can be `.tar.gz` format. In the future, we might switch to a proper package (e.g. `.deb`).

**Comment by mklgallegos** [comment] 2021-07-31 08:37
related to 
https://github.com/zenithdb/console/issues/125
https://github.com/zenithdb/console/issues/18

**Comment by hlinnaka** [comment] 2021-08-20 17:36
@ololobus, I'm assigning this to you because I think it's a duplicate of or at least overlaps https://github.com/zenithdb/console/issues/18. Feel free to close or split or something as you see fit.

**Comment by ololobus** [comment] 2021-08-20 18:06
Yeah, it somewhat overlaps and most of Eric's proposals are done:
- [x] we build Docker images with Zenith / Postgres binaries, but **after** successful release testing pipeline
- [x] we have a script to extract them from the image as a `.tar.gz` and deploy these binaries to the cloud storage fleet
- [ ] we **don't** put binaries used in the CI test jobs into final images, but build them in a separate Docker job. The main idea was to have an option to build image / binaries locally without CI, otherwise we got bound to it. Yet, **ship exactly what you test** feels as an absolutely right thing that we have to implement eventually

So maybe I can close this one and create a follow-up that will suggest:
- build release Docker images **before** testing and then use them for tests instead of current `build-release`
- push them to Docker Hub if tests passed and it was a commit to `main`

**Closed** 2021-08-30 11:57 UTC

**Comment by kelvich** [comment] 2021-08-30 12:01
Follow up: https://github.com/zenithdb/zenith/issues/487
