### ISSUE TITLE
`tried to request a page version that was garbage collected` in pageserver's walsender

### ISSUE THREAD

**Issue by kelvich** [zenithdb/zenith#1122] opened 2022-01-13 17:51 UTC
Sometimes during the safekeeper->pageserver replication wal_receiver may fail with the following error (right after connection start usually):
```
WAL streaming connection failed (tried to request a page version that
was garbage collected. requested at 0/2981A90 gc cutoff 0/E7C5190)
```

Reason is not clear =/ Could problems in GC or wrong replication start lsn selection.

**Comment by knizhnik** [comment] 2022-01-14 08:47
The reasons seems to be obvious: GC horizon is not somehow synchronized with safekeepers and even with disk consistent LSN which is not correct.
There is #1004 PR addressing last problem. But even with this PR there will be no warranty that safekeepers will not resend WAL record with LSN<=disk_consistent_lsn. And so pageserver doesn't know safe cutoff point for GC.

The obvious workaround is to make GC horizon=PiTR interval large enough, so that it never intersects with current replication position (making the most conservative assumption). Otherwise, I afraid that we should somehow extent replication protocol to report safe cutoff position.

**Comment by LizardWizzard** [comment] 2022-01-14 09:49
If I understand it correctly pageserver tried to start replication from lsn that is < latest_gc_cutoff. But in walreceiver we start point is set to last_record lsn or zero if nothing was streamed before. This is confusing. I do not get it how it is possible. It seems that there is no need for pageserver to request WAL older than gc cutoff

**Comment by LizardWizzard** [comment] 2022-01-14 10:03
Also this check might be too restrictive. Imagine if there is no newer version of a page, but due to activity on other pages/segments gc moved forward enough that this old image become older than current cutoff

**Comment by hlinnaka** [comment] 2022-01-14 18:07
Idea for reproducing this: Concurrently run pgbench or some other workload that requests pages, and in another thread call `do_gc` with 0 GC horizon in a loop. Might expose other interesting GC bugs too...

**Comment by stepashka** [comment] 2022-01-14 20:09
is regularly reproduced by the failing attempts to start the cluster on staging
timeline id 4cb7130ac08e2f2019fc919b4d9fe46b

**Comment by hlinnaka** [comment] 2022-01-14 23:38
I think this is a duplicate of https://github.com/zenithdb/zenith/issues/1047, closing this one

**Closed by hlinnaka** 2022-01-14 23:38 UTC
Labels: t/bug, c/safekeeper, c/pageserver

**Comment by knizhnik** [comment] 2022-01-15 14:07
With checkpoint_cs locked in timeline_gc I was not able to reproduce the problem with  pgbench and 8kb GC horizon and 1 sec GC/checkpoint interval
