### ISSUE TITLE
No way to terminate the data insert in the loop

### ISSUE THREAD

**Issue by stepashka** [zenithdb/zenith#1221] opened 2022-02-05 16:45 UTC
Create a table and try to insert the data inside:

```
CREATE TABLE distributors
(
    did  integer CHECK (did > 100),
    name varchar(40)
);

do
$$
    begin
        for i in 100000..100000000
            loop
                insert into distributors(did, name) values (i, i::text);
            end loop;
    end;
$$;
```

Get tired of waiting after 3 mins and try to stop the insert operation.

Expected: it stops
Actual: the command falls of with I/O error, further commands return "401 Unauthorized", cluster size on the web page continues to grow.

Additional details:
If I start and stop the cluster, the data growth stops, but I still get "401 Unauthorized" for any operation.

```
select count(*)
from distributors
```
does not show anything on the website's SQL editor.

`ctrl-c` analogue in the GUI SQL client was used to stop the clusters.
* On the first try, ignores things entirely
* On the second try, fails with
```
[2022-02-04 15:35:44] Cancelling…
[2022-02-04 15:39:01] An I/O error occurred while sending to the backend.
[2022-02-04 15:39:01] Unrecoverable error received, the connection is spoiled
```

`pg_cancel_backend` and `pg_terminate_backend` return `f` and do not cancel anything

Cluster: https://console.zenith.tech/app/clusters/wispy-dew-894465

filed on behalf of @SomeoneToIgnore

**Comment by hlinnaka** [comment] 2022-02-22 15:04
I cannot reproduce this now. I believe this was fixed by https://github.com/zenithdb/postgres/commit/d69332c9bfea2c603c57a6e8ec3bafcf72a45905, and/or enabling backpressure.

**Closed by hlinnaka** 2022-02-22 15:04 UTC
Labels: t/bug, c/storage/pageserver, m/bug-bash-feb22
