### ISSUE TITLE
Compute node doesn't survive a second restart

### ISSUE THREAD

**Issue by ololobus** [zenithdb/zenith#395] opened 2021-08-05 08:48 UTC
Follow up for #388.

With slightly updated repro script it hangs forever after a second restart: https://gist.github.com/ololobus/24af672d4892b19f4c4c802603cf7986

There is nothing suspicious in the logs at a first sight.

CC @arssher @knizhnik

**Comment by kelvich** [comment] 2021-08-05 11:06
Hm, I thought I posted backtrace of crash in decode_wal_record() with this script. Is that still reproducible?

**Comment by ololobus** [comment] 2021-08-05 12:03
This issue is reproducible, but I don't see a backtrace in the logs anymore.

Here is a backtrace I got once, so I do not think it's related (maybe create another issue? But without repro it isn't that useful):
```
thread 'WAL receiver thread' panicked at 'cannot advance past `remaining`: 91393 <= 65562', /Users/alexk/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-1.0.1/src/bytes.rs:539:9
stack backtrace:
   0:        0x110fd3964 - std::backtrace_rs::backtrace::libunwind::trace::h67b1783e93f517c7
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:        0x110fd3964 - std::backtrace_rs::backtrace::trace_unsynchronized::h6642b95f229b3f12
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x110fd3964 - std::sys_common::backtrace::_print_fmt::h0a233062426578e9
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x110fd3964 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5b5b7de1c79b4b45
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x110ff77ee - core::fmt::write::h65ec8c8a6aa7b549
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/fmt/mod.rs:1094:17
   5:        0x110fcc48a - std::io::Write::write_fmt::hc52e560ab9e57db4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/io/mod.rs:1584:15
   6:        0x110fd5caf - std::sys_common::backtrace::_print::h27e4664250aa8eaf
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x110fd5caf - std::sys_common::backtrace::print::hb149f667a3c579ca
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x110fd5caf - std::panicking::default_hook::{{closure}}::h0974624c30a6e2b5
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:208:50
   9:        0x110fd57b9 - std::panicking::default_hook::hda3cfa32e0773aac
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:225:9
  10:        0x110fd6315 - std::panicking::rust_panic_with_hook::h1cdaa4b48d8ea4a1
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:591:17
  11:        0x110fd5e55 - std::panicking::begin_panic_handler::{{closure}}::h51157b4dbc4c5d91
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:497:13
  12:        0x110fd3df8 - std::sys_common::backtrace::__rust_end_short_backtrace::h8f7fee8b4c5a0c05
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:141:18
  13:        0x110fd5dba - rust_begin_unwind
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
  14:        0x11100deef - core::panicking::panic_fmt::h28a37220b8fae52a
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
  15:        0x10fe26ceb - <bytes::bytes::Bytes as bytes::buf::buf_impl::Buf>::advance::hf12b447b30243c7e
                               at /Users/alexk/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-1.0.1/src/bytes.rs:539:9
  16:        0x10fe97d17 - pageserver::waldecoder::decode_wal_record::h0b5cc4dd0ec361cc
                               at /Users/alexk/dev/zenith/pageserver/src/waldecoder.rs:822:5
  17:        0x10ff39ade - pageserver::walreceiver::walreceiver_main::h38df629a3178a7ab
                               at /Users/alexk/dev/zenith/pageserver/src/walreceiver.rs:213:35
  18:        0x10ff37d8a - pageserver::walreceiver::thread_main::h05d7069a24d6d98e
                               at /Users/alexk/dev/zenith/pageserver/src/walreceiver.rs:106:19
  19:        0x10ff37a72 - pageserver::walreceiver::launch_wal_receiver::{{closure}}::hebd6f3c79763e778
                               at /Users/alexk/dev/zenith/pageserver/src/walreceiver.rs:71:21
  20:        0x10fedc012 - std::sys_common::backtrace::__rust_begin_short_backtrace::h72f1a8d421a80502
                               at /Users/alexk/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  21:        0x10fe35492 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h1616c32a3bb476da
                               at /Users/alexk/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/mod.rs:481:17
  22:        0x10fe7d852 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h40e8b29df07cf90d
                               at /Users/alexk/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panic.rs:344:9
  23:        0x10fea818b - std::panicking::try::do_call::he3881f971d108413
                               at /Users/alexk/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
  24:        0x10fec813b - ___rust_try
  25:        0x10fea8009 - std::panicking::try::hfce4b84e630d4998
                               at /Users/alexk/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
  26:        0x10fe7f3d2 - std::panic::catch_unwind::h96dce1e4e8dbff94
                               at /Users/alexk/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panic.rs:431:14
  27:        0x10fe34ffb - std::thread::Builder::spawn_unchecked::{{closure}}::h8565ef60e7aca0e1
                               at /Users/alexk/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/mod.rs:480:30
  28:        0x10fea8a31 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hd389db9667fdc881
                               at /Users/alexk/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  29:        0x110fdc6fd - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h5aa62e9e06fddcf4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/boxed.rs:1546:9
  30:        0x110fdc6fd - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1cedadddb09ad52f
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/boxed.rs:1546:9
  31:        0x110fdc6fd - std::sys::unix::thread::Thread::new::thread_start::h59fdfe326de12d08
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys/unix/thread.rs:71:17
  32:     0x7fff204e98fc - __pthread_start
Aug 04 20:18:18.073 ERRO socket error: unknown message tag: 102,'b"\0"'
```

**Comment by knizhnik** [comment] 2021-08-05 12:43
I think this crash can be caused by corrupted WAL record.
We are still not checking WAL record CRC in waldecoder.

**Comment by ololobus** [comment] 2021-08-05 14:50
Right now CI failed with a very similar symptom on pg_regress (getpage@lsn hung forever, i.e. until 10 min timeout): https://app.circleci.com/pipelines/github/zenithdb/zenith/1056/workflows/aa0a6b38-1444-4510-8ee6-1c5d75fe4951/jobs/5662/steps?invite=true#step-105-257

```
Too long with no output (exceeded 10m0s): context deadline exceeded
```

In pageserver.log:
```
Aug 05 14:18:20.511 INFO connected!, location: pageserver::walreceiver, pageserver/src/walreceiver.rs:132
Aug 05 14:18:20.511 INFO IdentifySystem { systemid: 6992947529560233701, timeline: 1, xlogpos: 0/F8BA988, dbname: None }, location: pageserver::walreceiver, pageserver/src/walreceiver.rs:144
Aug 05 14:18:20.512 INFO WAL streaming connection failed (WAL record crc mismatch at 0/F8B9369), retrying in 1 second, location: pageserver::walreceiver, pageserver/src/walreceiver.rs:109
Aug 05 14:18:21.512 INFO connecting to "host=127.0.0.1 port=55432 user=zenith_admin dbname=postgres", location: pageserver::walreceiver, pageserver/src/walreceiver.rs:125
Aug 05 14:18:21.513 INFO connected!, location: pageserver::walreceiver, pageserver/src/walreceiver.rs:132
Aug 05 14:18:21.514 INFO IdentifySystem { systemid: 6992947529560233701, timeline: 1, xlogpos: 0/F8BA988, dbname: None }, location: pageserver::walreceiver, pageserver/src/walreceiver.rs:144
Aug 05 14:18:21.514 INFO WAL streaming connection failed (WAL record crc mismatch at 0/F8B9369), retrying in 1 second, location: pageserver::walreceiver, pageserver/src/walreceiver.rs:109
Aug 05 14:18:22.514 INFO connecting to "host=127.0.0.1 port=55432 user=zenith_admin dbname=postgres", location: pageserver::walreceiver, pageserver/src/walreceiver.rs:125
Aug 05 14:18:22.516 INFO connected!, location: pageserver::walreceiver, pageserver/src/walreceiver.rs:132
Aug 05 14:18:22.516 INFO IdentifySystem { systemid: 6992947529560233701, timeline: 1, xlogpos: 0/F8BA988, dbname: None }, location: pageserver::walreceiver, pageserver/src/walreceiver.rs:144
Aug 05 14:18:22.517 INFO WAL streaming connection failed (WAL record crc mismatch at 0/F8B9369), retrying in 1 second, location: pageserver::walreceiver, pageserver/src/walreceiver.rs:109
Aug 05 14:18:22.848 ERRO get_page_at_lsn: Timed out while waiting for WAL record at LSN 0/F8B9370 to arrive. valid LSN in 0/F8B75C8, location: pageserver::page_service, pageserver/src/page_service.rs:294
Aug 05 14:18:22.848 ERRO get_page_at_lsn: Timed out while waiting for WAL record at LSN 0/F8B9370 to arrive. valid LSN in 0/F8B75C8, location: pageserver::page_service, pageserver/src/page_service.rs:294
Aug 05 14:18:22.848 ERRO get_page_at_lsn: Timed out while waiting for WAL record at LSN 0/F8B9370 to arrive. valid LSN in 0/F8B75C8, location: pageserver::page_service, pageserver/src/page_service.rs:294
Aug 05 14:18:22.848 ERRO get_page_at_lsn: Timed out while waiting for WAL record at LSN 0/F8B9370 to arrive. valid LSN in 0/F8B75C8, location: pageserver::page_service, pageserver/src/page_service.rs:294
Aug 05 14:18:22.848 ERRO get_page_at_lsn: Timed out while waiting for WAL record at LSN 0/F8B9370 to arrive. valid LSN in 0/F8B75C8, location: pageserver::page_service, pageserver/src/page_service.rs:294
Aug 05 14:18:22.848 ERRO get_page_at_lsn: Timed out while waiting for WAL record at LSN 0/F8B9370 to arrive. valid LSN in 0/F8B75C8, location: pageserver::page_service, pageserver/src/page_service.rs:294
Aug 05 14:18:22.848 ERRO get_page_at_lsn: Timed out while waiting for WAL record at LSN 0/F8B9370 to arrive. valid LSN in 0/F8B75C8, location: pageserver::page_service, pageserver/src/page_service.rs:294
Aug 05 14:18:22.848 ERRO get_page_at_lsn: Timed out while waiting for WAL record at LSN 0/F8B9370 to arrive. valid LSN in 0/F8B75C8, location: pageserver::page_service, pageserver/src/page_service.rs:294
Aug 05 14:18:22.848 ERRO get_page_at_lsn: Timed out while waiting for WAL record at LSN 0/F8B9370 to arrive. valid LSN in 0/F8B75C8, location: pageserver::page_service, pageserver/src/page_service.rs:294
Aug 05 14:18:22.848 ERRO get_page_at_lsn: Timed out while waiting for WAL record at LSN 0/F8B9370 to arrive. valid LSN in 0/F8B75C8, location: pageserver::page_service, pageserver/src/page_service.rs:294
Aug 05 14:18:22.848 ERRO get_page_at_lsn: Timed out while waiting for WAL record at LSN 0/F8B9370 to arrive. valid LSN in 0/F8B75C8, location: pageserver::page_service, pageserver/src/page_service.rs:294
Aug 05 14:18:22.849 INFO postgres backend to 127.0.0.1:55412 exited, location: zenith_utils::postgres_backend, zenith_utils/src/postgres_backend.rs:174
Aug 05 14:18:22.849 INFO postgres backend to 127.0.0.1:55372 exited, location: zenith_utils::postgres_backend, zenith_utils/src/postgres_backend.rs:174
Aug 05 14:18:22.849 INFO postgres backend to 127.0.0.1:55402 exited, location: zenith_utils::postgres_backend, zenith_utils/src/postgres_backend.rs:174
Aug 05 14:18:22.849 INFO postgres backend to 127.0.0.1:55406 exited, location: zenith_utils::postgres_backend, zenith_utils/src/postgres_backend.rs:174
Aug 05 14:18:22.849 INFO postgres backend to 127.0.0.1:55378 exited, location: zenith_utils::postgres_backend, zenith_utils/src/postgres_backend.rs:174
Aug 05 14:18:22.849 INFO postgres backend to 127.0.0.1:55382 exited, location: zenith_utils::postgres_backend, zenith_utils/src/postgres_backend.rs:174
Aug 05 14:18:22.849 INFO postgres backend to 127.0.0.1:55416 exited, location: zenith_utils::postgres_backend, zenith_utils/src/postgres_backend.rs:174
Aug 05 14:18:22.849 INFO postgres backend to 127.0.0.1:55396 exited, location: zenith_utils::postgres_backend, zenith_utils/src/postgres_backend.rs:174
Aug 05 14:18:22.849 ERRO get_page_at_lsn: Timed out while waiting for WAL record at LSN 0/F8B9370 to arrive. valid LSN in 0/F8B75C8, location: pageserver::page_service, pageserver/src/page_service.rs:294
Aug 05 14:18:22.850 ERRO get_page_at_lsn: Timed out while waiting for WAL record at LSN 0/F8B9370 to arrive. valid LSN in 0/F8B75C8, location: pageserver::page_service, pageserver/src/page_service.rs:294
Aug 05 14:18:22.851 INFO postgres backend to 127.0.0.1:55404 exited, location: zenith_utils::postgres_backend, zenith_utils/src/postgres_backend.rs:174
Aug 05 14:18:23.517 INFO connecting to "host=127.0.0.1 port=55432 user=zenith_admin dbname=postgres", location: pageserver::walreceiver, pageserver/src/walreceiver.rs:125
Aug 05 14:18:23.518 INFO connected!, location: pageserver::walreceiver, pageserver/src/walreceiver.rs:132
Aug 05 14:18:23.519 INFO IdentifySystem { systemid: 6992947529560233701, timeline: 1, xlogpos: 0/F8BABA0, dbname: None }, location: pageserver::walreceiver, pageserver/src/walreceiver.rs:144
Aug 05 14:18:23.519 INFO WAL streaming connection failed (WAL record crc mismatch at 0/F8B9369), retrying in 1 second, location: pageserver::walreceiver, pageserver/src/walreceiver.rs:109
```

@knizhnik, if your newly added in #396 crc check is correct, then what is the source of corrupt WAL records?

**Comment by knizhnik** [comment] 2021-08-09 06:48
>  if your newly added in #396 crc check is correct, then what is the source of corrupt WAL records?
WAL may not be completely written (some WAL record is only partly received)

**Comment by knizhnik** [comment] 2021-08-09 06:57
I have found two problems in wal proposer:
1. It always starts replication from the beginning of segment. It was done for "safety" but this approach doesn't work with "synthetic" WA: generated by page server. 
2. WalProposerPoll doesn't check return code of WaitEventSetWait which cause infinite connect-disconnect loop

Both problems are fixed by commit [7e752b2285]. 
But script is still hangs. Looks like it is some race condition because adding "sleep 1" 
allows script to complete normally.
I am going to investigate it more if I will have free time.

**Comment by knizhnik** [comment] 2021-08-10 08:52
I have fixed few more bugs in walkeeper and walproposer:  walkeeper is not saving restart_lsn in storage and walpropser performs unnecessary recovery. But it doesn't completely solve the problem with race condition. If compute node is shutdowned before it was able to broadcast all WAL to walkeepers, then we are in trouble.
I will continue investigations, but @arssher  can also be interested in it.

**Comment by ololobus** [comment] 2021-08-10 13:59
@knizhnik, thanks! Have you pushed it somewhere? I don't see relevant PRs or commits in the `main` since your last introduction of CRC checking

**Comment by knizhnik** [comment] 2021-08-11 06:22
Sorry, now I pushed this fixes to postgres and zenith repositories.

**Comment by kelvich** [comment] 2021-09-02 13:43
Related: https://github.com/zenithdb/zenith/issues/439

**Closed** 2021-11-01 08:16 UTC
Labels: bug
